version: '3.8'

services:
  mongo:
    networks:
      - kafka-network
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  mongo-express:
    networks:
      - kafka-network
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  zookeeper:
    networks:
      - kafka-network
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    networks:
      - kafka-network
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE_LISTENER: PLAINTEXT
      KAFKA_LISTENER_NAME_OUTSIDE_LISTENER: PLAINTEXT_HOST

  akhq:
    networks:
      - kafka-network
    image: tchiotludo/akhq
    user: "1000:1000"
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: localhost:9092

  order-service:
    networks:
      - kafka-network
    build: .
    container_name: order-service
    depends_on:
      - mongo
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/orders
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

networks:
  kafka-network:
    driver: bridge