version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  akhq:
    image: tchiotludo/akhq
    platform: linux/amd64
    ports:
      - "8081:8081"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            port: 8081
          connections:
            local-kafka:
              properties:
                bootstrap.servers: kafka:9092

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - mongo
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/orders
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
